# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: ack-controller-aws-factory
description: An AWS Factory using ACK
home: https://github.com/portefaix/portefaix-hub/charts/ack-controller-aws-factory
# icon:
type: application
version: 0.1.0
appVersion: "1.5.0"
keywords:
  - cloud
  - infrastructure
  - aws
  - ack
maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com
    url: https://github.com/nlamirault
# https://artifacthub.io/docs/topics/repositories/
annotations:
  artifacthub.io/changes: |
    - AWS Factory deployment
  artifacthub.io/links: |
    - name: kubernetes
      url: https://aws-controllers-k8s.github.io/community/
    - name: Portefaix
      url: https://portefaix.xyz
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
