# Default values for ack-controller-aws-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for ack-controller-aws-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Additional labels to add to all resources
additionalLabels:
  app: aws-ack-controller

# -- Additional annotations to add to all resources
additionalAnnotations: {}
  # monitoring: portefaix

aws:
  vpc:
    # -- The IPv4 network range for the VPC, in CIDR notation
    cidr: 10.1.0.0/16
    # -- default tags for VPC
    tags:
      Service: vpc
