---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  name: {{ include "ack-controller-aws-factory.name" . }}
  namespace: {{ template "ack-controller-aws-factory.namespace" . }}
  labels:
    {{- include "ack-controller-aws-factory.labels" . | nindent 4 }}
  annotations:
    services.k8s.aws/region: {{ .Values.aws.region }}
    {{- with .Values.additionalAnnotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  cidrBlock: $CIDR_BLOCK
  vpcID: $VPC_ID