---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aws-adot-amp.fullname" . }}
  namespace: {{ template "aws-adot-amp.namespace" . }}
  labels:
    {{- include "aws-adot-amp.labels" . | indent 4 }}
data:
  adot-collector-config: |
    {{- toYaml .Values.config | nindent 4 }}
