---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aws-adot-amp.fullname" . }}
  namespace: {{ template "aws-adot-amp.namespace" . }}
  labels:
    {{- include "aws-adot-amp.labels" . | indent 4 }}
data:
  adot-collector-config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s

          scrape_configs:
          - job_name: 'kubernetes-service-endpoints'

            kubernetes_sd_configs:
            - role: endpoints

            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

            relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_scrape]
              action: keep
              regex: true

    exporters:
      awsprometheusremotewrite:
        # replace this with your endpoint
        endpoint: "<YOUR_ENDPOINT>"
        # replace this with your region
        aws_auth:
          region: "<YOUR_REGION>"
          service: "aps"
        namespace: "adot"
      logging:
        loglevel: debug

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [logging, awsprometheusremotewrite]
