---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "fluxcd-mixin.fullname" .) "rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "fluxcd-mixin.namespace" . }}
  annotations:
{{ include "fluxcd-mixin.annotations" . | indent 4 }}
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "fluxcd-mixin.labels" . | indent 4 }}
spec:
  groups: []
